name: Lab05
run-name: Lab05
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: load_repository
        uses: actions/checkout@v4
      - name: Build
        run: cd banking && cmake -H. -B build && cmake --build build

      - name: Test
        run: cd banking && git submodule add https://github.com/google/googletest third-party/gtest && cmake -H. -B build -DBUILD_TESTS=ON && cmake --build build --target test

