name: Lab05
run-name: Lab05
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: load_repository
        uses: actions/checkout@v4
      - name: Build
        run: cd banking && && cmake -H. -B build && cmake --build build

      # - name: Test
      #   working-directory: ${{github.workspace}}/build
      #   run: ctest -C ${{env.BUILD_TYPE}}

